name: update and release

on:
    push:
        branches: ["main"]
    schedule:
        - cron: "0 12 * * 1"
    workflow_dispatch:

jobs:
    update-and-release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup deno @ v1
              uses: denoland/setup-deno@v1
              with:
                  deno-version: v1.x

            - name: Update and release 🚀
              run: deno task run
              env: 
                  GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
